/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CmdAgentImpl */

#ifndef _Included_CmdAgentImpl
#define _Included_CmdAgentImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef CmdAgentImpl_serialVersionUID
#define CmdAgentImpl_serialVersionUID -3215090123894869218i64
#undef CmdAgentImpl_serialVersionUID
#define CmdAgentImpl_serialVersionUID -4100238210092549637i64
#undef CmdAgentImpl_serialVersionUID
#define CmdAgentImpl_serialVersionUID 4974527148936298033i64
/*
 * Class:     CmdAgentImpl
 * Method:    C_GetLocalTime
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_CmdAgentImpl_C_1GetLocalTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CmdAgentImpl
 * Method:    C_GetLocalOS
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_CmdAgentImpl_C_1GetLocalOS
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
